[options]
    colorscheme = "gruvbox"
    background = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = false
    enable_statusline_display_mode = true
    enable_cursorcolumn = 1
    terminal_cursor_shape = 1


[[layers]]
name = "default"

[[layers]]
name = 'core'

[[layers]]
name = 'core#banner'

[[layers]]
name = 'core#statusline'

[[layers]]
name = 'core#tabline'

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'checkers'
show_cursor_error = false

[[layers]]
name = 'edit'

[[layers]]
name = 'format'

[[layers]]
name = 'denite'

[[layers]]
  name = "git"

[[layers]]
name = "tags"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'ui'

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#java"


[[custom_plugins]]
name = 'sheerun/vim-polyglot'
merged = 0
